channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.5
  - tensorflow-gpu=2.0.0
  - pillow=6.2.1
  - jupyter=1.0.0
  - noise=1.2.2
  - scikit-image=0.15.0
  - pip=19.3.1
  - pip:
      - opencv-python
